### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dajare** [idikiy/mignon-g-eberhart_the-patient-in-room-18#1]
### misc, typography, semantics

- [x] re-run `se modernize-spelling` and commit the changes (using `[Editorial]` message); it should find two instances of `bandan[-n-]a`.
- [x] re-run `se semanticate` and commit the changes in cc 9 and 14; you'll need to revert its tweak in c12.
- [x] re-run `se build-images` and commit change (it looks like you forgot to re-run this after adding the corrected 1400x2100 cover jpg). 
- [x] c5/123: for `is a ⸻?` -> `is a⁠—?` (In the scans, this is just a broken-off dialog, not a full-word obscured.)
- [x] c6/112 : remove ` epub:type="z3998:article"`: we don't use/need this semantic for newspaper reports; the bare `blockquote` suffices.
- [x] c7/35: for `‘disapp’⁠—eared` -> `‘disapp’-eared` (Just a [hyphen](https://standardebooks.org/manual/1.8.4/single-page#8.7.7.3) needed here: this was what was in the scans, and originally in the transcription, as it happens.)

### content.opf

- [x] You need to add the [Haycraft-Queen Cornerstones][hq] set to the metadata. See any of the previous titles for copy/paste code. 

### Rebase

- [x] 16eb7d0 - the commit message needs to be re-worded from "Manual typography changes  - Chapter titles" to "Semantics for all chapter titles"
- [x] 16d470e - this is the first "Manually add additional semantics" commit, but you have mixed in `[Editorial]` commits as well:
  - [c2/15](https://github.com/idikiy/mignon-g-eberhart_the-patient-in-room-18/commit/16d470efb35714a7f262dcc956116edcc5e3abe8#diff-b2f61a1d58d902a67c3b65797391739450b013c8fee897bc57427e3feb5b4caeL15) `twelve-thirty` -> `twelve thirty` is not "semantics", but an editorial change to typography so also the following: c2/42, c2/121
  - you'll need to "edit" this commit, reverting those changes, and committing separately in an `[Editorial]` commit. You might combine this with the same issue in the next item:
- [x] 5980413 - this also needs the message tweaked: from "Manual typography for initials and times" to "Manual semantics for initials and times"
  - **Nota bene**: this commit has mixed in `[Editorial]` changes, just like the one above (all like `one-thirty` -> `one thirty`):
  c3/41, c3/81, c3/126, c3/144, c3/229; c5/148; c7/121, c7/134, c7/138

### Comments

- Normally, the sections of styling in `local.css` are wrapped with comments, e.g. `/* Begin Letters */`; you can see how it looks in [this example][css]. Since there isn't much here, we can leave your `local.css` as-is, but worth having this convention on your radar.
- You did a good job on the descriptions. `:)` Alex usually is quite active in editing these (especially the long description), but what you have is pretty well-judged.
- Some SE conventions changed since you embarked on the project in July. That created some aggro for you, but it all came good to my eye. Hopefully your next project won't suffer from that problem!

[css]: https://github.com/standardebooks/honore-de-balzac_parisians-in-the-country_ellen-marriage/blob/master/src/epub/css/local.css
[hq]: https://standardebooks.org/collections/haycraft-queen-cornerstones

**Comment by dajare** [comment]
@idikiy Anything I can do to help with this? It would be great to get this project wrapped up and released. Hope all's well at your end!

**Comment by idikiy** [comment]
Thanks, David.  I'm very new to Git so I could use a pointer for the rebasing steps.  I think I figured out how to edit the commit descriptions but some steps for splitting out different changes into another commit would be helpful.  Even a pointer to a relevant guide would be welcome.  I'll work on the other changes which I believe are just edits that can be captured in new commits.

**Comment by dajare** [comment]
I had only used git casually before getting stuck in with Std Ebooks, and rebasing made me break out in a cold sweat. Now ... not so much. `:-)` Renaming (editing commit messages) is relatively straightforward, I'd suggest trying that to start with. You could review Vince's advice in from [this project](https://github.com/chapkachapka/dorothy-m-richardson_honeycomb/issues/1#issuecomment-2041149774), although he gets a bit nitty-gritty with particulars, so it might be hard to generalize to your case from that. Still, worth reading through!

IMPORTANTLY! like Vince says, **Always, always, ALWAYS make a local backup of your repository.** That is, copy the WHOLE project directory to a different location in your local drive, *then* (and only then!) do your rebase steps. Then, if anything goes wrong, you can just **copy** back the repo from it's backup location and try again.

- [This guide](https://www.sitepoint.com/git-interactive-rebase-guide/) will be a help with the "renaming" exercise.
- "Splitting" and editing a commit is trickier, but I've needed to do it once or twice, and [the tutorial here](https://www.bryanbraun.com/2019/02/23/editing-a-commit-in-an-interactive-rebase/) got me through safely.
- **N.b.** after a successful rebase operation, you need to use `git push --force origin main` (I believe that's the correct wording for your repo) to push your commits to GitHub: normal `push` won't be sufficient.

Hopefully that's enough to get you going. Please come back to me if you get stuck, but ... these guides should get you through! `:-)`

**Comment by idikiy** [comment]
Thanks for the advice, this should be a good place to start.  I believe I've changed the commit message for the former "Manual typography changes - Chapter titles" commit.  Of course all the commit numbers are different now.

When I am splitting out the [Editorial] changes from the next commits, should I combine multiple [Editorial] changes in to one commit, or keep the separate?  It sounds like most of them are adding hyphens to time values.

**Comment by dajare** [comment]
Yes, rebases will change the commit ID's, unfortunately. If you have your backup copy of the repo before the rebase, that gives you something to compare with (but the messages should still make clear what's needed).

You can group together "like" pieces of work: the important thing is NOT to mix Editorial with non-Editorial. If you have a set of "add hyphens" (or "remove hyphens"), they can be commited together with the `[Editorial]` prefix in the commit message.

Hope that helps, and glad you're making progress!

**Comment by idikiy** [comment]
OK, I followed Vince's advice in that issue and split out the editorial changes into a separate commit.  Unfortunately, they are now placed before the "Manually add additional semantics" commit.  Please let me know if the order is an issue.  Otherwise, I think I addressed all the issues.  I would appreciate it if you could check again.

**Comment by dajare** [comment]
Order of commits is no problem in this situation, so well done on that difficult operation!

There's still an issue with the commit message of 9bff403 I'm afraid. You've currently got it as `Manually add additional semantics` but there's quite a bit more than semantics in that commit. Fortunately, none of it is "Editorial" `:)` so a simple rename of this commit should do it. I'd suggest: `Changes to semantics, typography, and formatting`. 

Could you ping me when that's done? I think with that finished, it will be ready for Alex.

**Comment by idikiy** [comment]
@dajare That should be done now.  Thanks a lot for all your help!

**Comment by dajare** [comment]
@idikiy - well done persevering! `:)` I'll let Alex know I think this is ready for his attention.
